---
title: "DS202_lab3"
author: "Kenneth Mendoza"
date: "October 3, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,eval=FALSE}
happy <- readRDS("HAPPY.rds")
```

```{r,eval=FALSE}
names(happy) = tolower(names(happy))
```

#1
```{r,eval=FALSE}
happy[ happy == "IAP" ] <- NA #replaces values in PolViews that are "IAP" to NA
happy[ happy == "DK" ] <- NA #replaces values in PolViews that are "DK" to NA
happy[ happy == "NA" ] <- NA #replaces values in PolViews that are "NA" to NA

head(happy, 10)
```

#2
```{r,eval=FALSE}
class(happy$HAPPY)
levels(factor(happy$HAPPY))
```
```{r,eval=FALSE}
class(happy$YEAR)
```
```{r,eval=FALSE}
class(happy$AGE)
happy[ happy == "89 OR OLDER" ] <- 89
happy$AGE <- as.numeric(as.character(happy$AGE))
```

```{r,eval=FALSE}
class(happy$SEX)
```

```{r,eval=FALSE}
class(happy$MARITAL)
```

```{r,eval=FALSE}
class(happy$DEGREE)
```

```{r,eval=FALSE}
class(happy$FINRELA)
```

```{r,eval=FALSE}
class(happy$HEALTH)
```

```{r,eval=FALSE}
class(happy$WTSSALL)
```

```{r,eval=FALSE}
class(happy$PARTYID)
```

```{r,eval=FALSE}
class(happy$POLVIEWS)
```


#3
```{r,eval=FALSE}
unique(happy$HAPPY)
```

```{r,eval=FALSE}
unique(happy$SEX)
```

```{r,eval=FALSE}
unique(happy$MARITAL)
```

```{r,eval=FALSE}
unique(happy$DEGREE)
```

```{r,eval=FALSE}
unique(happy$FINRELA)
```

```{r,eval=FALSE}
unique(happy$HEALTH)
```

```{r,eval=FALSE}
unique(happy$PARTYID)
```

```{r,eval=FALSE}
unique(happy$POLVIEWS)
```


##Part 2
#1

```{r}
happy$age <- as.numeric(as.character(happy$age))
ggplot(data = happy, aes(x = age, color = sex)) + geom_histogram(binwidth = 2) + facet_wrap(~sex) + ggtitle("Number of Survey Takers vs Age")

ggplot(data = happy, aes(x = year)) + geom_histogram(binwidth = 5) + facet_wrap(~sex) + ggtitle("Number of People vs Year")
```

```{r}
happy <- happy[complete.cases(happy[, 'happy']), ]

# plot 1

ggplot(data = happy, aes(x = age)) + facet_wrap(~happy) + geom_histogram(binwidth = 1)

#plot 2

ggplot(data = happy, aes(x = degree), stat = 'count') + facet_wrap(~happy) + geom_bar(mapping = aes(fill = degree))
 + coord_flip() + labs(title = "Happiness Based on Degree Obtained")
```

```{r}
# plot 2

```















